# =============================================================================
# Damage Number - Individual floating combat text
# Generated by VEILBREAKERS Animation System
# =============================================================================

class_name DamageNumber
extends Node2D

signal finished

@export var label: Label
@export var shadow_label: Label
@export var lifetime: float = 1.0
@export var fade_start: float = 0.6
@export var bounce_on_crit: bool = true
@export var scale_pop: float = 1.3

var _velocity: Vector2 = Vector2.ZERO
var _gravity: float = 0.0
var _elapsed: float = 0.0
var _is_critical: bool = false
var _base_scale: Vector2 = Vector2.ONE
var _original_font_size: int = 0

func _ready() -> void:
	_base_scale = scale

	# Auto-find label if not assigned
	if not label and has_node("Label"):
		label = get_node("Label")
	if not shadow_label and has_node("Shadow"):
		shadow_label = get_node("Shadow")

	# Store original font size for reset on reuse
	if label:
		_original_font_size = label.get_theme_font_size("font_size")

func setup(config: Dictionary, velocity: Vector2, gravity: float) -> void:
	_velocity = velocity
	_gravity = gravity
	_elapsed = 0.0
	_is_critical = config.get("is_critical", false)

	# Reset font size to original (prevents accumulation on pool reuse)
	# Handle edge case where original font size is 0 (no override set)
	if label:
		if _original_font_size > 0:
			label.add_theme_font_size_override("font_size", _original_font_size)
		else:
			# Remove any override to use theme default
			label.remove_theme_font_size_override("font_size")

	# Set text
	var text = ""
	if config.has("text"):
		text = config.text
	else:
		text = config.get("prefix", "") + str(config.get("value", 0)) + config.get("suffix", "")

	if label:
		label.text = text
	if shadow_label:
		shadow_label.text = text

	# Set color
	if label:
		label.modulate = config.get("color", Color.WHITE)

	# Scale
	var scale_mult = config.get("scale_mult", 1.0)
	if _is_critical:
		scale_mult *= 1.3
	_base_scale = Vector2.ONE * scale_mult

	# Initial pop animation
	scale = _base_scale * scale_pop
	modulate.a = 1.0

	var tween = create_tween()
	tween.tween_property(self, "scale", _base_scale, 0.15).set_ease(Tween.EASE_OUT)

	# Crit bounce
	if _is_critical and bounce_on_crit:
		_velocity.y *= 0.5  # Less initial upward, more bounce
		if label:
			var current_size = label.get_theme_font_size("font_size")
			label.add_theme_font_size_override("font_size", current_size + 8)

func _process(delta: float) -> void:
	_elapsed += delta

	# Physics
	_velocity.y += _gravity * delta
	position += _velocity * delta

	# Crit bounce
	if _is_critical and _velocity.y > 0 and position.y > 0:
		_velocity.y *= -0.5
		position.y = 0

	# Fade out
	if _elapsed > fade_start:
		var fade_progress = (_elapsed - fade_start) / (lifetime - fade_start)
		modulate.a = 1.0 - fade_progress

	# Finish
	if _elapsed >= lifetime:
		finished.emit()
