# =============================================================================
# Damage Number - AAA Floating Combat Text
# Generated by VEILBREAKERS Animation System
# =============================================================================

class_name DamageNumber
extends Node2D

signal finished
signal critical_hit_triggered(position: Vector2, damage: int)  # For screen shake

@export var label: Label
@export var shadow_label: Label
@export var glow_label: Label  # Optional glow layer
@export var particles: GPUParticles2D  # Optional crit particles
@export var lifetime: float = 1.0
@export var fade_start: float = 0.6
@export var bounce_on_crit: bool = true
@export var scale_pop: float = 1.3

# AAA Polish Settings
@export_group("AAA Effects")
@export var enable_damage_scaling: bool = true  # Scale font by damage amount
@export var min_damage_for_scaling: int = 50  # Start scaling above this
@export var max_scale_damage: int = 500  # Cap scaling at this damage
@export var max_font_scale: float = 1.8  # Maximum font scale multiplier
@export var enable_glow: bool = true
@export var glow_intensity: float = 0.6
@export var crit_glow_pulse: bool = true

var _velocity: Vector2 = Vector2.ZERO
var _gravity: float = 0.0
var _elapsed: float = 0.0
var _is_critical: bool = false
var _base_scale: Vector2 = Vector2.ONE
var _original_font_size: int = 0
var _damage_value: int = 0
var _base_color: Color = Color.WHITE
var _glow_tween: Tween = null


func _ready() -> void:
	_base_scale = scale

	# Auto-find nodes if not assigned
	if not label and has_node("Label"):
		label = get_node("Label")
	if not shadow_label and has_node("Shadow"):
		shadow_label = get_node("Shadow")
	if not glow_label and has_node("Glow"):
		glow_label = get_node("Glow")
	if not particles and has_node("CritParticles"):
		particles = get_node("CritParticles")

	# Store original font size for reset on reuse
	if label:
		_original_font_size = label.get_theme_font_size("font_size")


func setup(config: Dictionary, velocity: Vector2, gravity: float) -> void:
	_velocity = velocity
	_gravity = gravity
	_elapsed = 0.0
	_is_critical = config.get("is_critical", false)
	_damage_value = config.get("value", 0)
	_base_color = config.get("color", Color.WHITE)

	# Kill any existing glow tween
	if _glow_tween and _glow_tween.is_valid():
		_glow_tween.kill()
		_glow_tween = null

	# Reset font size to original (prevents accumulation on pool reuse)
	if label:
		if _original_font_size > 0:
			label.add_theme_font_size_override("font_size", _original_font_size)
		else:
			label.remove_theme_font_size_override("font_size")

	# Set text
	var text := ""
	if config.has("text"):
		text = config.text
	else:
		text = config.get("prefix", "") + str(_damage_value) + config.get("suffix", "")

	if label:
		label.text = text
	if shadow_label:
		shadow_label.text = text
	if glow_label:
		glow_label.text = text

	# Set color
	if label:
		label.modulate = _base_color
	if glow_label and enable_glow:
		glow_label.modulate = Color(_base_color, glow_intensity)
		glow_label.visible = true
	elif glow_label:
		glow_label.visible = false

	# === AAA: Damage-based font scaling ===
	var scale_mult: float = config.get("scale_mult", 1.0)
	if enable_damage_scaling and _damage_value >= min_damage_for_scaling:
		var damage_factor := clampf(
			float(_damage_value - min_damage_for_scaling) / float(max_scale_damage - min_damage_for_scaling),
			0.0, 1.0
		)
		var font_scale := lerpf(1.0, max_font_scale, damage_factor)
		scale_mult *= font_scale

	if _is_critical:
		scale_mult *= 1.4  # Slightly bigger for crits

	_base_scale = Vector2.ONE * scale_mult

	# Initial pop animation with elastic bounce
	scale = _base_scale * scale_pop
	modulate.a = 1.0

	var tween := create_tween()
	tween.tween_property(self, "scale", _base_scale, 0.2).set_ease(Tween.EASE_OUT).set_trans(Tween.TRANS_ELASTIC)

	# === AAA: Critical hit effects ===
	if _is_critical and bounce_on_crit:
		_velocity.y *= 0.5  # Less initial upward, more bounce
		if label:
			var current_size := label.get_theme_font_size("font_size")
			label.add_theme_font_size_override("font_size", current_size + 12)

		# Emit signal for screen shake
		critical_hit_triggered.emit(global_position, _damage_value)

		# Spawn particles if available
		if particles:
			particles.emitting = true

		# Glow pulse animation for crits
		if glow_label and crit_glow_pulse:
			_start_glow_pulse()


func _start_glow_pulse() -> void:
	## Pulsing glow effect for critical hits
	if not glow_label:
		return

	_glow_tween = create_tween()
	_glow_tween.set_loops(3)
	_glow_tween.tween_property(glow_label, "modulate:a", glow_intensity * 1.5, 0.1)
	_glow_tween.tween_property(glow_label, "modulate:a", glow_intensity * 0.3, 0.1)


func _process(delta: float) -> void:
	_elapsed += delta

	# Physics
	_velocity.y += _gravity * delta
	position += _velocity * delta

	# Crit bounce
	if _is_critical and _velocity.y > 0 and position.y > 0:
		_velocity.y *= -0.5
		position.y = 0

	# Fade out
	if _elapsed > fade_start:
		var fade_progress = (_elapsed - fade_start) / (lifetime - fade_start)
		modulate.a = 1.0 - fade_progress

	# Finish
	if _elapsed >= lifetime:
		finished.emit()
