# =============================================================================
# Screen Effects Manager
# Central hub for all screen-space visual effects
# Generated by VEILBREAKERS Animation MCP
# =============================================================================

class_name ScreenEffectsManager
extends Control

# -----------------------------------------------------------------------------
# SIGNALS
# -----------------------------------------------------------------------------
signal effect_started(effect_name: String)
signal effect_finished(effect_name: String)

# -----------------------------------------------------------------------------
# NODE REFERENCES (Assign in editor)
# -----------------------------------------------------------------------------
@export_group("Effect Layers")
@export var flash_rect: ColorRect  # For screen flashes
@export var vignette_rect: ColorRect  # For damage vignette
@export var chromatic_rect: ColorRect  # For chromatic aberration
@export var fade_rect: ColorRect  # For scene transitions
@export var letterbox_top: ColorRect  # Cinematic bars
@export var letterbox_bottom: ColorRect

@export_group("Shader Materials")
@export var chromatic_material: ShaderMaterial
@export var vignette_material: ShaderMaterial
@export var crt_material: ShaderMaterial  # Optional retro effect

# -----------------------------------------------------------------------------
# CONFIGURATION
# -----------------------------------------------------------------------------
@export_group("Flash Settings")
@export var default_flash_duration: float = 0.1
@export var crit_flash_color: Color = Color(1, 1, 1, 0.4)
@export var damage_flash_color: Color = Color(1, 0.2, 0.2, 0.3)
@export var heal_flash_color: Color = Color(0.2, 1, 0.4, 0.2)
@export var capture_flash_color: Color = Color(1, 0.9, 0.2, 0.5)

@export_group("Vignette Settings")
@export var low_health_threshold: float = 0.3
@export var vignette_pulse_speed: float = 2.0

@export_group("Chromatic Aberration")
@export var chromatic_intensity: float = 3.0
@export var chromatic_duration: float = 0.2

@export_group("Letterbox")
@export var letterbox_height: float = 80.0
@export var letterbox_speed: float = 0.3

# -----------------------------------------------------------------------------
# STATE
# -----------------------------------------------------------------------------
var _current_health_percent: float = 1.0
var _is_letterboxed: bool = false
var _active_effects: Dictionary = {}
var _effect_tweens: Dictionary = {}

# -----------------------------------------------------------------------------
# LIFECYCLE
# -----------------------------------------------------------------------------
func _ready() -> void:
	_initialize_effects()

func _process(delta: float) -> void:
	_update_vignette(delta)

func _initialize_effects() -> void:
	# Start with all effects invisible
	if flash_rect:
		flash_rect.modulate.a = 0
	if vignette_rect:
		vignette_rect.modulate.a = 0
	if chromatic_rect and chromatic_material:
		chromatic_material.set_shader_parameter("aberration_amount", 0.0)
	if fade_rect:
		fade_rect.modulate.a = 0
	
	# Hide letterbox
	if letterbox_top:
		letterbox_top.position.y = -letterbox_height
	if letterbox_bottom:
		letterbox_bottom.position.y = get_viewport().get_visible_rect().size.y

# -----------------------------------------------------------------------------
# SCREEN FLASH
# -----------------------------------------------------------------------------
func flash(color: Color = Color.WHITE, duration: float = -1.0) -> void:
	if not flash_rect:
		return
	
	if duration < 0:
		duration = default_flash_duration
	
	_cancel_effect("flash")
	
	flash_rect.color = Color(color.r, color.g, color.b, 1.0)
	flash_rect.modulate.a = color.a
	
	var tween = create_tween()
	tween.tween_property(flash_rect, "modulate:a", 0.0, duration)
	_effect_tweens["flash"] = tween
	
	effect_started.emit("flash")
	tween.finished.connect(func(): effect_finished.emit("flash"))

func flash_crit() -> void:
	flash(crit_flash_color, 0.08)

func flash_damage() -> void:
	flash(damage_flash_color, 0.15)

func flash_heal() -> void:
	flash(heal_flash_color, 0.2)

func flash_capture() -> void:
	flash(capture_flash_color, 0.3)

func flash_custom(color: Color, duration: float, hold_time: float = 0.0) -> void:
	"""Flash with optional hold before fade"""
	if not flash_rect:
		return
	
	_cancel_effect("flash")
	
	flash_rect.color = Color(color.r, color.g, color.b, 1.0)
	flash_rect.modulate.a = color.a
	
	var tween = create_tween()
	if hold_time > 0:
		tween.tween_interval(hold_time)
	tween.tween_property(flash_rect, "modulate:a", 0.0, duration)
	_effect_tweens["flash"] = tween

# -----------------------------------------------------------------------------
# VIGNETTE (Low health indicator)
# -----------------------------------------------------------------------------
func set_health_percent(percent: float) -> void:
	_current_health_percent = clamp(percent, 0.0, 1.0)

func _update_vignette(delta: float) -> void:
	if not vignette_rect or not vignette_material:
		return
	
	if _current_health_percent > low_health_threshold:
		vignette_rect.modulate.a = lerp(vignette_rect.modulate.a, 0.0, delta * 5.0)
		return
	
	# Calculate intensity based on health
	var health_factor = 1.0 - (_current_health_percent / low_health_threshold)
	
	# Pulsing effect
	var pulse = (sin(Time.get_ticks_msec() * 0.001 * vignette_pulse_speed * PI * 2.0) + 1.0) * 0.5
	var intensity = health_factor * (0.5 + pulse * 0.5)
	
	vignette_rect.modulate.a = intensity * 0.8
	
	if vignette_material:
		vignette_material.set_shader_parameter("health_percent", _current_health_percent)

func pulse_vignette(intensity: float = 0.5, duration: float = 0.3) -> void:
	"""One-shot vignette pulse (for hits)"""
	if not vignette_rect:
		return
	
	var original_alpha = vignette_rect.modulate.a
	vignette_rect.modulate.a = intensity
	
	var tween = create_tween()
	tween.tween_property(vignette_rect, "modulate:a", original_alpha, duration)

# -----------------------------------------------------------------------------
# CHROMATIC ABERRATION
# -----------------------------------------------------------------------------
func chromatic_aberration(intensity: float = -1.0, duration: float = -1.0) -> void:
	if not chromatic_rect or not chromatic_material:
		return
	
	if intensity < 0:
		intensity = chromatic_intensity
	if duration < 0:
		duration = chromatic_duration
	
	_cancel_effect("chromatic")
	
	chromatic_material.set_shader_parameter("aberration_amount", intensity)
	
	var tween = create_tween()
	tween.tween_method(
		func(val): chromatic_material.set_shader_parameter("aberration_amount", val),
		intensity,
		0.0,
		duration
	)
	_effect_tweens["chromatic"] = tween
	
	effect_started.emit("chromatic")
	tween.finished.connect(func(): effect_finished.emit("chromatic"))

func chromatic_hit() -> void:
	"""Quick chromatic burst for getting hit"""
	chromatic_aberration(2.0, 0.15)

func chromatic_crit() -> void:
	"""Stronger chromatic for critical damage"""
	chromatic_aberration(4.0, 0.2)

# -----------------------------------------------------------------------------
# SCENE TRANSITIONS
# -----------------------------------------------------------------------------
func fade_out(color: Color = Color.BLACK, duration: float = 0.5) -> Signal:
	if not fade_rect:
		# Return a signal that completes immediately to prevent await deadlock
		var dummy_tween = create_tween()
		dummy_tween.tween_callback(func(): pass)
		return dummy_tween.finished
	
	_cancel_effect("fade")
	
	fade_rect.color = color
	fade_rect.modulate.a = 0
	
	var tween = create_tween()
	tween.tween_property(fade_rect, "modulate:a", 1.0, duration)
	_effect_tweens["fade"] = tween
	
	effect_started.emit("fade_out")
	return tween.finished

func fade_in(duration: float = 0.5) -> Signal:
	if not fade_rect:
		# Return a signal that completes immediately to prevent await deadlock
		var dummy_tween = create_tween()
		dummy_tween.tween_callback(func(): pass)
		return dummy_tween.finished
	
	_cancel_effect("fade")
	
	var tween = create_tween()
	tween.tween_property(fade_rect, "modulate:a", 0.0, duration)
	_effect_tweens["fade"] = tween
	
	effect_started.emit("fade_in")
	return tween.finished

func crossfade(duration: float = 1.0) -> void:
	"""Fade out then back in"""
	await fade_out(Color.BLACK, duration * 0.5)
	await fade_in(duration * 0.5)

func fade_to_color(color: Color, duration: float = 0.3) -> Signal:
	if not fade_rect:
		return Signal()
	
	fade_rect.color = color
	var tween = create_tween()
	tween.tween_property(fade_rect, "modulate:a", 1.0, duration)
	return tween.finished

# -----------------------------------------------------------------------------
# LETTERBOX (Cinematic bars)
# -----------------------------------------------------------------------------
func show_letterbox(duration: float = -1.0) -> void:
	if duration < 0:
		duration = letterbox_speed
	
	_is_letterboxed = true
	
	var viewport_height = get_viewport().get_visible_rect().size.y
	
	if letterbox_top:
		var tween_top = create_tween()
		tween_top.tween_property(letterbox_top, "position:y", 0, duration).set_ease(Tween.EASE_OUT)
	
	if letterbox_bottom:
		var tween_bottom = create_tween()
		tween_bottom.tween_property(letterbox_bottom, "position:y", viewport_height - letterbox_height, duration).set_ease(Tween.EASE_OUT)
	
	effect_started.emit("letterbox")

func hide_letterbox(duration: float = -1.0) -> void:
	if duration < 0:
		duration = letterbox_speed
	
	_is_letterboxed = false
	
	var viewport_height = get_viewport().get_visible_rect().size.y
	
	if letterbox_top:
		var tween_top = create_tween()
		tween_top.tween_property(letterbox_top, "position:y", -letterbox_height, duration).set_ease(Tween.EASE_IN)
	
	if letterbox_bottom:
		var tween_bottom = create_tween()
		tween_bottom.tween_property(letterbox_bottom, "position:y", viewport_height, duration).set_ease(Tween.EASE_IN)
	
	effect_finished.emit("letterbox")

func toggle_letterbox() -> void:
	if _is_letterboxed:
		hide_letterbox()
	else:
		show_letterbox()

# -----------------------------------------------------------------------------
# COMBINED EFFECTS (Presets)
# -----------------------------------------------------------------------------
func on_player_hit(damage_percent: float = 0.1) -> void:
	"""All effects for when player takes damage"""
	flash_damage()
	pulse_vignette(0.3 + damage_percent * 0.5, 0.2)
	chromatic_hit()

func on_player_crit_hit() -> void:
	"""Effects for critical hit on player"""
	flash(Color(1, 0, 0, 0.5), 0.2)
	pulse_vignette(0.7, 0.3)
	chromatic_crit()

func on_enemy_death() -> void:
	"""Effects when enemy dies"""
	flash(Color(1, 1, 1, 0.2), 0.15)

func on_boss_phase_change() -> void:
	"""Dramatic phase transition"""
	show_letterbox()
	await get_tree().create_timer(0.2).timeout
	flash(Color.WHITE, 0.3)
	chromatic_aberration(5.0, 0.4)

func on_capture_success() -> void:
	"""Capture celebration"""
	flash_capture()
	await get_tree().create_timer(0.1).timeout
	flash(Color.WHITE, 0.2)

func on_level_up() -> void:
	"""Level up celebration"""
	flash(Color(1, 0.9, 0.3, 0.4), 0.3)

# -----------------------------------------------------------------------------
# UTILITY
# -----------------------------------------------------------------------------
func _cancel_effect(effect_name: String) -> void:
	if _effect_tweens.has(effect_name):
		var tween = _effect_tweens[effect_name]
		if tween and tween.is_valid():
			tween.kill()
		_effect_tweens.erase(effect_name)

func cancel_all_effects() -> void:
	for effect_name in _effect_tweens.keys():
		_cancel_effect(effect_name)
	
	# Reset states
	if flash_rect:
		flash_rect.modulate.a = 0
	if chromatic_material:
		chromatic_material.set_shader_parameter("aberration_amount", 0.0)
